### ISSUE TITLE
Image embeddings problem

### ISSUE THREAD

**Issue by NaevdeSeidhe** [pagekeytech/onenote-to-markdown#13]
I used the script on win11 with the intention to import my older OneNote-notes in Obsidian.
It worked well, except for the images.

Obsidian doesn't recognize for example:
`![](media/image1.png){width="9.604166666666666in"` `height="0.34375in"}`

![image](https://github.com/pagekey/onenote-to-markdown/assets/123672577/9b1f3e54-1c4a-4ebd-87a2-ea5ac787c814)

+ the image-names aren't unique, i got the image-names like "image001" again and again for each folder which I think creates problems when linking in Obsidian.

---

Just as a personal feedback :) thanks for creating and sharing the script

**Comment by stephengrice** [comment]
Thanks for writing this up! Definitely appreciate the feedback. Sorry for never replying. I have moved this issue over to our PageKey GitLab, so I'm going to close it out here: https://gitlab.com/pagekey/edu/onenote-to-markdown/-/issues/5

Thanks again!
