### ISSUE TITLE
Retrieving the COM class factory for component with CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E} failed due to the following error: 80080005 Server  execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).

### ISSUE THREAD

**Issue by ianrego** [pagekeytech/onenote-to-markdown#8]
onenote-to-markdown> .\convert3.ps1

`
New-Object : Retrieving the COM class factory for component with CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E} failed due to the following error: 80080005 Server 
execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
At C:\Notebooks\Polytek\onenote-to-markdown\convert3.ps1:7 char:12
+ $OneNote = New-Object -ComObject OneNote.Application
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand
 
You cannot call a method on a null-valued expression.
At C:\Notebooks\Polytek\onenote-to-markdown\convert3.ps1:9 char:1
+ $OneNote.GetHierarchy("", [Microsoft.Office.InterOp.OneNote.Hierarchy ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
`

**Comment by mrtabaa** [comment]
The same issue. Have you found a solution?

**Comment by ianrego** [comment]
No. I've moved to the desktop version.

**Comment by mrtabaa** [comment]
Running both OneNote and PowerShell as Administrator has resolved my issue. I'd appreciate your update if it works or not. 

I used this method for the OneNote to md (Obsidian) conversion. 
https://github.com/theohbrothers/ConvertOneNote2MarkDown

**Comment by gustavostz** [comment]
I was having the same problem and running both OneNote and PowerShell as Administrator as @mrtabaa mentioned has resolved my issue as well

**Comment by stephengrice** [comment]
Moving this issue to PageKey GitLab: https://gitlab.com/pagekey/edu/onenote-to-markdown/-/issues/4
